export const ACTIVITIES_BY_USER = 'ACTIVITIES_BY_USER';
export const ACTIVITIES_BY_USER_PROGRESS = 'ACTIVITIES_BY_USER_PROGRESS';
export const ACTIVITIES_BY_USER_DONE = 'ACTIVITIES_BY_USER_DONE';
export const ACTIVITIES_BY_USER_PENDING = 'ACTIVITIES_BY_USER_PENDING';
export const HISTORY_ACTIVITIES = 'HISTORY_ACTIVITIES';
export const TEMP_ACTIVITIES = 'TEMP_ACTIVITIES';
export const DASHBOARD_ACTIVITIES_PROGRESS = 'DASHBOARD_ACTIVITIES_PROGRESS';
export const DASHBOARD_ACTIVITIES_DONE = 'DASHBOARD_ACTIVITIES_DONE';
export const DASHBOARD_ACTIVITIES_PENDING = 'DASHBOARD_ACTIVITIES_PENDING';
export const DASHBOARD_ACTIVITIES_EMPLOYEE = 'DASHBOARD_ACTIVITIES_EMPLOYEE';

export const DASHBOARD_ACTIVITIES_PROGRESS_MONTHLY =
  'DASHBOARD_ACTIVITIES_PROGRESS_MONTHLY';
export const DASHBOARD_ACTIVITIES_DONE_MONTHLY =
  'DASHBOARD_ACTIVITIES_DONE_MONTHLY';
export const DASHBOARD_ACTIVITIES_PENDING_MONTHLY =
  'DASHBOARD_ACTIVITIES_PENDING_MONTHLY';

export const SELECT_REGIONAL = 'SELECT_REGIONAL';
export const SET_DATA_STATUS = 'SET_DATA_STATUS';

export const ACTIVITIES = 'ACTIVITIES';
export const SELECTED_ACTIVITIES = 'SELECTED_ACTIVITIES';
export const DASHBOARD_ACTIVITIES = 'DASHBOARD_ACTIVITIES';
export const LOADING = 'LOADING';
export const MESSAGE = 'MESSAGE';
export const ERROR = 'ERROR';
export const MONTH = 'MONTH';
export const YEAR = 'YEAR';
export const REGIONAL_ID = 'REGIONAL_ID';
